###
GET http://localhost:8080/api/member?page=0&size=10
Content-Type: application/json

###
POST http://localhost:8080/api/member
Content-Type: application/json

{
  "nickname": "회원닉네임 작성",
  "addr": "주소1",
  "addrDetail": "주소상세1"
}

###
PUT http://localhost:8080/api/member/7
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nickname": "회원닉네임 수정",
  "addr": "주소 수정1",
  "addrDetail": "주소 상세 수정1"
}